name: "composie action. check and verify cache."
description: "Check cache"
inputs:
  operatingsystem:
    default: 'Windows'
    required: false
  architecture:
    default: 'all'
    required: false
  md5sums:
    default: 'd41d8cd98f00b204e9800998ecf8427e  ...multline-string...'
    required: false
  keyfile:
    default: 'urls.txt'
    required: false
env:
  WINPTY_URL: https://github.com/rprichard/winpty/releases/download/0.4.3/winpty-0.4.3-msvc2015.zip
runs:
  using: "composite" # caller os is ubuntu-xxx
  steps:
    - name: init
      shell: bash
      run: |
        touch urls.txt && truncate --size 0 urls.txt
        echo '5.4.2' >> urls.txt
        echo ${{ env.WINPTY_URL }} >> urls.txt
        echo  '1.0.19' >> urls.txt
        file urls.txt
        cat urls.txt
    - name: Restore cache /${{ env.arc }}
      uses: actions/cache/restore@v4
        with:
          enableCrossOsArchive: true
          path: downloads
          key: ${{ inputs.operatingsystem }}-${{ inputs.architecture }}-${{ hashFiles('urls.txt') }}
        env:
          os: ${{ inputs.operatingsystem }}
          arc: ${{ inputs.architecture }}
          ky: ${{ hashFiles('urls.txt') }}
          keyfile: ${{ inputs.keyfile }}
          key: ${{ hashFiles(${{ inputs.keyfile }}) }}
          REPO: ${{ github.repository }}
    - name: Verify cache /${{ env.arc }}
      id: verifycache
      continue-on-error: true
      shell: bash {0}
      run: |
        test -d cache-${{ env.arc }} && rm -rf cache-${{ env.arc }}
        test -d cache-${{ env.arc }} || mkdir cache-${{ env.arc }}
        find downloads -type f -exec cp \{\} ./cache-${{ env.arc }} \;
        echo "${{ inputs.md5sums }}" > MD5SUMS-${{ env.arc }}
        cd ./cache-${{ env.arc }}
        md5sum -c ../MD5SUMS-${{ env.arc }}
        if [ $? -gt 0 ]; then
          echo "cache=invalid" >> $GITHUB_OUTPUT
        else
          echo "cache=valid" >> $GITHUB_OUTPUT
        fi
        echo "### VerifyCache :rocket:" >> $GITHUB_STEP_SUMMARY
      env:
        arc: ${{ inputs.architecture }}
        os: Windows
        keyfile: ${{ inputs.keyfile }}
        REPO: ${{ github.repository }}
    - name: show result /${{ env.arc }}
      shell: bash
      run: |
        echo 'cache status:' ${{ steps.verifycache.outputs.cache }}
    - name: ${{ env.arc }} / Use current cache
      if: steps.verifycache.outputs.cache == 'valid'
      shell: bash
      run: |
        echo "repository cache is fine."
        echo "KEY: ${{ env.os }}-${{ env.arc }}-${{ hashFiles($keyfile) }}"
        echo "### NotUpdateCache :rocket:" >> $GITHUB_STEP_SUMMARY
      env:
        arc: ${{ inputs.architecture }}
        os: Windows
        keyfile: ${{ inputs.keyfile }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO: ${{ github.repository }}
    - name: ${{ env.arc }} / todo Download missing dependencies
      if: steps.verifycache.outputs.cache == 'invalid'
      shell: bash
      run: |
        echo "repository cache is bad."
        echo "KEY: ${{ env.os }}-${{ env.arc }}-${{ hashFiles($keyfile) }}"
        echo "### TodoUpdateCache :rocket:" >> $GITHUB_STEP_SUMMARY
      env:
        arc: ${{ inputs.architecture }}
        os: Windows
        keyfile: ${{ inputs.keyfile }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO: ${{ github.repository }}
