name: 'x-screendump'
description: "Force Upload some files"
runs:
  using: "composite"
  steps:
    - name: Force Upload some files (x: prefix github.workspace)
      uses: actions/upload-artifact@v4
      with:
        # Name of the artifact to upload.
        name: x-${{ github.workflow }}-${{ github.job }}-${{ join(matrix.*, '-') }}-some-files
        # A file, directory or wildcard pattern that describes what
        # to upload.
        path: |
         ${{ github.workspace }}/runtime/syntax/testdir/input/sh_*
         ${{ github.workspace }}/src/testdir/test_r*
        # The desired behavior if no files are found using the
        # provided path.
        if-no-files-found: ignore
        # Duration after which artifact will expire in days. 0 means
        # using repository settings.
        retention-days: 0
        # If true, an artifact with a matching name will be deleted
        overwrite: true
    - name: Force Upload some files (y: prefix none)
      uses: actions/upload-artifact@v4
      with:
        # Name of the artifact to upload.
        name: y-${{ github.workflow }}-${{ github.job }}-${{ join(matrix.*, '-') }}-some-files
        # A file, directory or wildcard pattern that describes what
        # to upload.
        path: |
         runtime/syntax/testdir/input/sh_*
         src/testdir/test_r*
        # The desired behavior if no files are found using the
        # provided path.
        if-no-files-found: ignore
        # Duration after which artifact will expire in days. 0 means
        # using repository settings.
        retention-days: 0
        # If true, an artifact with a matching name will be deleted
        overwrite: true
    - name: Force Upload some files (z: tilde expansion)
      uses: actions/upload-artifact@v4
      with:
        # Name of the artifact to upload.
        name: y-${{ github.workflow }}-${{ github.job }}-${{ join(matrix.*, '-') }}-some-files
        # A file, directory or wildcard pattern that describes what
        # to upload.
        path: |
         ~/runtime/syntax/testdir/input/sh_*
         ~/src/testdir/test_r*
        # The desired behavior if no files are found using the
        # provided path.
        if-no-files-found: ignore
        # Duration after which artifact will expire in days. 0 means
        # using repository settings.
        retention-days: 0
        # If true, an artifact with a matching name will be deleted
        overwrite: true
