name: Cache check windows

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      runid:
        required: true
        type: string
    outputs:
      restore-key:
        description: "use this KEY for cache, Windows-{arch}-KEY"
        value: ${{ jobs.windows-cache.outputs.restore-key }}

concurrency:
  # The concurrency group contains the workflow name and the branch name for
  # pull requests or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  windows-cache:
    runs-on: ubuntu-latest
    env:
      thisworkflowname: Cache check windows
      usage: caller_workflow.jobs.xxx.uses ./.github/workflow/called_workflow.yml
      # Lua
      LUA_VER: 54
      LUA_VER_DOT: '5.4'
      LUA_RELEASE: 5.4.2
      LUA32_URL: https://downloads.sourceforge.net/luabinaries/lua-%LUA_RELEASE%_Win32_dllw6_lib.zip
      LUA64_URL: https://downloads.sourceforge.net/luabinaries/lua-%LUA_RELEASE%_Win64_dllw6_lib.zip
      # winpty
      WINPTY_URL: https://github.com/rprichard/winpty/releases/download/0.4.3/winpty-0.4.3-msvc2015.zip
      # libsodium
      SODIUM_VER: '1.0.19'
      SODIUM_MSVC_URL: https://download.libsodium.org/libsodium/releases/libsodium-%SODIUM_VER%-stable-msvc.zip
      SODIUM_MSVC_VER: v143
      SODIUM_MINGW_URL: https://download.libsodium.org/libsodium/releases/libsodium-%SODIUM_VER%-stable-mingw.tar.gz
      SODIUM_MINGW_VER: 26
    outputs:
      restore-key: ${{ steps.validkey.outputs.restore-key }}

    steps:
      - name: Initialize
        id: init
        run: |
          # pseudo matrix. first x86, then x64 serial run.
          echo "x86arch=x86" >> $GITHUB_OUTPUT
          echo "x86bits=32" >> $GITHUB_OUTPUT
          echo "x64arch=x64" >> $GITHUB_OUTPUT
          echo "x64bits=64" >> $GITHUB_OUTPUT
      - name: Key file (list of download URLs)
        run: |
          touch urls.txt
          echo ${{ env.LUA_RELEASE }} >> urls.txt
          echo ${{ env.WINPTY_URL }}  >> urls.txt
          echo ${{ env.SODIUM_VER }}  >> urls.txt
          sed -i 's/$/\r/g' urls.txt
          test -d downloads || mkdir downloads

      - name: Restore Cache ${{ env.arch }}
        id: restorecache86
        uses: actions/cache/restore@v4
        with:
          path: downloads
          key: ${{ runner.os }}-${{ env.arch }}-runid_${{ inputs.runid }}
          restore-keys: |
            ${{ runner.os }}-${{ env.arch }}-${{ hashFiles('urls.txt') }}
            ${{ runner.os }}-${{ env.arch }}-runid_
        env:
          arch: ${{ steps.init.outputs.x86arch }}

      - name: Download dependencies ${{ env.arch }}
        if: ${{ steps.restorecache86.outputs.cache-matched-key == '' }}
        run: |
          dlfile2 () {
            if [ -f downloads/$2 ];then
              echo Skip Downlaod. $2
            else
              wget -nv --tries=2 --retry-wait=10 -O $2 $1
            fi
          }
          test -d downloads || mkdir downloads
          dlfile2 ${{ env.LUA32_URL }} downloads/lua.zip
          ls -lahgG downloads

      - name: Rename cachedir ${{ env.arch }}
        shell: bash
        run: |
          echo 'restore key is:'
          echo ${{ steps.restorecache86.outputs.cache-matched-key }}
          test -d downloads && mv downloads cache_${{ env.arch }}
          test -d downloads || mkdir cache_${{ env.arch }}
          ls -lagG cache_${{ env.arch }}
        env:
          arch: ${{ steps.init.outputs.x86arch }}

      - name: Verify cache ${{ env.arch }}
        if: ${{ steps.restorecache86.outputs.cache-matched-key != '' }}
        id: verifycache
        shell: bash
        continue-on-error: true
        run: |
          cd cache_${{ env.arch }}
          touch MD5SUMS
          cat <<EOM > MD5SUMS
          x86::8867b0380daabd12ece3dbad73197e78  libsodium.tar.gz
          x86::113f036c91f06a9fdb11186e3dce7d93  libsodium.zip
          x86::25b07e2b5177a2f071f109f641f9e3e4  lua.zip
          x86::a0f941c53b8e509712eeca46104674c4  winpty.zip
          x64::8867b0380daabd12ece3dbad73197e78  libsodium.tar.gz
          x64::113f036c91f06a9fdb11186e3dce7d93  libsodium.zip
          x64::132834e89206d893630410fa2192bd2a  lua.zip
          x64::a0f941c53b8e509712eeca46104674c4  winpty.zip
          EOM
          sed -i '/^x64/ s,^,#,' MD5SUMS
          sed -i '/^x86/ s,^x86::,,' MD5SUMS
          md5sum -c MD5SUMS
          if $?
            echo "cache status: valid"
          else
            echo "cache status: valid"
          fi
        env:
          arch: ${{ steps.init.outputs.x86arch }}

      - name: return valid KEY ${{ env.arch }}
        id: validkey
        run: |
          echo "restore-key=UNKNOWN" >> $GITHUB_OUTPUT






