name: print ubuntu update-alternatives with setup-ruby

on:
  workflow_dispatch:

jobs:
  printenv:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
        with:
          repository: svardew/vim
          path: vim
      - name: Run a one-line script
        run: uname -a
      - name: p update-alter
        shell: bash {0}
        run: |
          echo '/** no ruby entry in update-alternatives.'
          echo ' * first upd-alt --install ruby'
          echo ' */'
          echo '```' >> $GITHUB_STEP_SUMMARY
          which ruby >> $GITHUB_STEP_SUMMARY
          ls -lah $(which ruby) >> $GITHUB_STEP_SUMMARY
          # lrwxrwxrwx 1 root root /usr/bin/ruby -> ruby3.0
          sudo update-alternatives --install /usr/bin/ruby ruby /usr/bin/ruby3.0  30
          sudo update-alternatives --set ruby /usr/bin/ruby3.0
          # /u/b/ruby3.0 provide /usr/bin/ruby (ruby) auto mode
          echo '```' >> $GITHUB_STEP_SUMMARY
      - name: setup-ruby 3.1.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.1
      - name: check rubies
        shell: bash {0}
        run: |
          which ruby
          ruby -v
          update-alternatives --query ruby
      - name: p update-alter
        shell: bash {0}
        run: |
          echo '/** add ruby entry into update-alternatives.'
          echo ' * which ruby (from PATH) is /opt/toolchain/... via setup-ruby'
          echo ' */'
          echo '```' >> $GITHUB_STEP_SUMMARY
          which ruby >> $GITHUB_STEP_SUMMARY
          ls -lah $(which ruby) >> $GITHUB_STEP_SUMMARY
          sudo update-alternatives --install /usr/bin/ruby ruby $(which ruby) 100         sudo update-alternatives --set ruby /usr/bin/ruby3.0
          update-alternatives --query ruby
          echo '```' >> $GITHUB_STEP_SUMMAR
