name: print ubuntu update-alternatives with setup-ruby

on:
  workflow_dispatch:

jobs:
  printenv:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
        with:
          repository: svardew/vim
          path: vim
      - name: Run a one-line script
        run: uname -a
      - name: p update-alter
        shell: bash {0}
        run: |
          echo '/** no ruby entry in update-alternatives.'
          echo ' * first upd-alt --install ruby'
          echo ' */'
          echo '```' >> $GITHUB_STEP_SUMMARY
          which ruby >> $GITHUB_STEP_SUMMARY
          ls -lah $(which ruby) >> $GITHUB_STEP_SUMMARY
          # lrwxrwxrwx 1 root root /usr/bin/ruby -> ruby3.0
          # sudo update-alternatives --install ruby ...
          sudo update-alternatives --install /usr/bin/ruby ruby /usr/bin/ruby3.0  100
          sudo update-alternatives --set ruby /usr/bin/ruby3.0
          echo '```' >> $GITHUB_STEP_SUMMARY
          
