name: Manual workflow

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: 'Person to greet'
        # default: 'World'
        default: '{["aa","ss","dd","ff"]}'
        required: true
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: with JSON
      run: |
        uname -a
        echo "J SON ?"
        echo $JSONSTR
      env:
        JSONSTR: ${{ join(fromJSON('["this","is","apen"]'), '\n') }}
