name: call composite-action
on:
  workflow_dispatch:
env:
  LUA_RELEASE: '5.4.2'
  WINPTY_URL: https://github.com/rprichard/winpty/releases/download/0.4.3/winpty-0.4.3-msvc2015.zip
  SODIUM_VER: '1.0.19'

jobs:
  composite_test:
    runs-on: ubuntu-22.04
    permissions:
      actions: write
      contents: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
      - name: init
        id: init
        shell: bash {0}
        run: |
          test -d downloads || mkdir downloads
          touch urls.txt && truncate --size 0 urls.txt
          echo ${{ env.LUA_RELEASE }} >> urls.txt
          echo ${{ env.WINPTY_URL }} >> urls.txt
          echo ${{ env.SODIUM_VER }} >> urls.txt
          sed -i 's/$/\r/g' urls.txt
          # checksum
          touch MD5SUMS
          cat <<EOF > MD5SUMS-all
          25b07e2b5177a2f071f109f641f9e3e4  lua-5.4.2_Win32_dllw6_lib.zip
          132834e89206d893630410fa2192bd2a  lua-5.4.2_Win64_dllw6_lib.zip
          a0f941c53b8e509712eeca46104674c4  winpty-0.4.3-msvc2015.zip
          2a0669a0596b7d8b8b2b9a775b479132  libsodium-1.0.19-mingw.tar.gz
          38db0856f7e3f9679f5e61c80632aac2  libsodium-1.0.19-msvc.zip
          EOF
          cat <<EOF > MD5SUMS-x86
          25b07e2b5177a2f071f109f641f9e3e4  lua.zip
          a0f941c53b8e509712eeca46104674c4  winpty.zip
          2a0669a0596b7d8b8b2b9a775b479132  libsodium.tar.gz
          38db0856f7e3f9679f5e61c80632aac2  libsodium.zip
          EOF
          cat <<EOF > MD5SUMS-x64
          132834e89206d893630410fa2192bd2a  lua.zip
          a0f941c53b8e509712eeca46104674c4  winpty.zip
          2a0669a0596b7d8b8b2b9a775b479132  libsodium.tar.gz
          38db0856f7e3f9679f5e61c80632aac2  libsodium.zip
          EOF
          #
          file urls.txt
          cat urls.txt

      - name: composite-action ${{ env.architecture }}
        id: verify-all
        uses: ./.github/actions/cache-check-verify
        with:
          restorekey: Windows-all-${{ hashFiles('urls.txt') }}
          architecture: 'all'
        env:
          architecture: 'all'

      - name: composite-action ${{ env.architecture }}
        id: verify-x86
        uses: ./.github/actions/cache-check-verify
        with:
          restorekey: Windows-x86-${{ hashFiles('urls.txt') }}
          architecture: 'x86'
        env:
          architecture: 'x86'

      - name: composite-action ${{ env.architecture }}
        id: verify-x64
        uses: ./.github/actions/cache-check-verify
        with:
          restorekey: Windows-x64-${{ hashFiles('urls.txt') }}
          architecture: 'x64'
        env:
          architecture: 'x64'

      - name: show summary
        run: |
          echo $cachestatus_all
          echo $cachestatus_x86
          echo $cachestatus_x64
        env:
          cachestatus_all: ${{ steps.verify-all.outputs.cachestatus }}
          cachestatus_x86: ${{ steps.verify-x86.outputs.cachestatus }}
          cachestatus_x64: ${{ steps.verify-x64.outputs.cachestatus }}

      - name: install actions/gh-actions-cache
        run: |
          gh extension install actions/gh-actions-cache
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: composite-action, pt2 ${{ env.architecture }}
        if: ${{ env.flag }} != 'valild'
        run: |
          gh actions-cache list -R $REPO
          # restorekey: Windows-all-${{ hashFiles('urls.txt') }}
          # architecture: 'all'
          # ?xflag? ${{ env.xflag }}
        env:
          architecture: 'all'
          flag: ${{ steps.verify-all.outputs.cachestatus }}
          xflag: ${{ steps.verify-${{ env.architecture }}.outputs.cachestatus }}
          REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

