name: call composite-action
on:
  workflow_dispatch:

jobs:
  composite_test:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
      - name: composite-action
        uses: ./.github/actions/cache-check-verify

