name: composite action using upload-artifact

on:
  push:
    branches:
      - try-uploadartifact
  workflow_dispatch: {}

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for
  # pull requests or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  linux:
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'workflow_dispatch' }}

    env:
      CC: ${{ matrix.compiler }}
      GCC_VER: 13
      CLANG_VER: 18
      TEST: test
      SRCDIR: ./src
      LEAK_CFLAGS: -DEXITFREE
      LOG_DIR: ${{ github.workspace }}/logs
      TERM: xterm
      DISPLAY: ':99'
      DEBIAN_FRONTEND: noninteractive
      SPARSE_CHECKOUT_DIR: .github_sparce_checkout

    strategy:
      fail-fast: false
      matrix:
        features: [tiny, normal, huge]
        compiler: [clang, gcc]
        extra: [[]]
        # Only use non-native architecture when features != huge.
        # features=huge tries to install python3-dev, which fails to install
        # for the non-native architecture.
        architecture: [native]
        include:
          - features: tiny
          - features: normal
          - features: huge

    steps:
      - name: Checkout repository from github
        uses: actions/checkout@v4
        with:
          repository: svardew/vim

      - name: Checkout sparse files for actions and workflows
        uses: actions/checkout@v4
        with:
          repository: svardew/hou
          ref: try-uploadartifact
          path: ${{ env.SPARSE_CHECKOUT_DIR }}
          sparse-checkout: |
            .github/actions/x-screendump/action.yml

      - name: add composite action
        run: |
          mv -vn ${{ env.SPARSE_CHECKOUT_DIR }}/.github/actions/x-screendump ./.github/actions/

      - name: force upload-artifact
        uses: ./.github/actions/x-screendump

  macos:
    runs-on: ${{ matrix.runner }}
    if: ${{ github.event_name == 'workflow_dispatch' }}

    env:
      CC: clang
      TEST: test
      SRCDIR: ./src
      LEAK_CFLAGS: -DEXITFREE
      TERM: xterm
      SPARSE_CHECKOUT_DIR: .github_sparce_checkout

    strategy:
      fail-fast: false
      matrix:
        features: [tiny, normal, huge]
        runner: [macos-12, macos-14]

    steps:
      - name: Checkout repository from github
        uses: actions/checkout@v4
        with:
          repository: svardew/vim

      - name: Checkout sparse files for actions and workflows
        uses: actions/checkout@v4
        with:
          repository: svardew/hou
          ref: try-uploadartifact
          path: ${{ env.SPARSE_CHECKOUT_DIR }}
          sparse-checkout: |
            .github/actions/x-screendump/action.yml

      - name: add composite action
        run: |
          mv -vn ${{ env.SPARSE_CHECKOUT_DIR }}/.github/actions/x-screendump ./.github/actions/

      - name: force upload-artifact
        uses: ./.github/actions/x-screendump

  windows:
    runs-on: windows-2022
    if: ${{ github.event_name == 'workflow_dispatch' }}

    env:
      # Escape sequences
      COL_RED: "\x1b[31m"
      COL_GREEN: "\x1b[32m"
      COL_YELLOW: "\x1b[33m"
      COL_RESET: "\x1b[m"
      SPARSE_CHECKOUT_DIR: .github_sparce_checkout

    strategy:
      fail-fast: false
      matrix:
        include:
          - { features: HUGE,   toolchain: msvc,  VIMDLL: no,  GUI: no,  arch: x64, python3: stable }
          - { features: HUGE,   toolchain: mingw, VIMDLL: yes, GUI: yes, arch: x86, python3: stable, coverage: yes }
          - { features: HUGE,   toolchain: msvc,  VIMDLL: no,  GUI: yes, arch: x86 }
          - { features: HUGE,   toolchain: mingw, VIMDLL: yes, GUI: no,  arch: x64, coverage: yes }
          - { features: NORMAL, toolchain: msvc,  VIMDLL: yes, GUI: no,  arch: x86 }
          - { features: NORMAL, toolchain: mingw, VIMDLL: no,  GUI: yes, arch: x64 }
          - { features: TINY,   toolchain: msvc,  VIMDLL: yes, GUI: yes, arch: x64 }
          - { features: TINY,   toolchain: mingw, VIMDLL: no,  GUI: no,  arch: x86 }

    steps:
      - name: Initialize
        id: init
        shell: bash
        run: |
          # Show Windows version
          cmd /c ver

          git config --global core.autocrlf input

      - name: Checkout repository from github
        uses: actions/checkout@v4
        with:
          repository: svardew/vim

      - name: Checkout sparse files for actions and workflows
        uses: actions/checkout@v4
        with:
          repository: svardew/hou
          ref: try-uploadartifact
          sparse-checkout: |
           .github/actions/x-screendump/action.yml

      - name: add composite action
        shell: cmd
        run: |
          xcopy .\${{ env.SPARSE_CHECKOUT_DIR }}\.github\actions\x-screendump\  .\.github\actions\  /f /s

      - name: force upload-artifact
        uses: ./.github/actions/x-screendump


