name: env ref
on:
  workflow_dispatch:

jobs:
  ee:
    runs-on: ubuntu-latest
    env:
      url: https://0.0.0.0/${{ env.Foo }}/
      Foo: pages
    steps:
      - name: echox
        run: |
          echo tgtt
          echo $Foo

        