name: env ref
on:
  workflow_dispatch:
  push:
    branches: ['**']


jobs:
  exoe:
    runs-on: ubuntu-latest
    env:
      Foo: pages
      Url: file:///tmp/${{ env.Url }}
    steps:
      - name: echox
        run: |
          echo tgtt
          echo ${{ env.Foo }}

        